USE [master]
GO

/****** Object:  Database [RecipeApp]    Script Date: 11.06.2023 23:47:39 ******/
CREATE DATABASE [RecipeApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RecipeApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RecipeApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RecipeApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RecipeApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RecipeApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RecipeApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RecipeApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RecipeApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RecipeApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RecipeApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [RecipeApp] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [RecipeApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RecipeApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RecipeApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RecipeApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RecipeApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RecipeApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RecipeApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RecipeApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RecipeApp] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RecipeApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RecipeApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RecipeApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RecipeApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RecipeApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RecipeApp] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [RecipeApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RecipeApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RecipeApp] SET  MULTI_USER 
GO

ALTER DATABASE [RecipeApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RecipeApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RecipeApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RecipeApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RecipeApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RecipeApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RecipeApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RecipeApp] SET  READ_WRITE 
GO


